// ActionTypes.js

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_FAILURE = 'GET_ORDER_BY_ID_FAILURE';

export const GET_USERS_ORDERS_REQUEST = 'GET_USERS_ORDERS_REQUEST';
export const GET_USERS_ORDERS_SUCCESS = 'GET_USERS_ORDERS_SUCCESS';
export const GET_USERS_ORDERS_FAILURE = 'GET_USERS_ORDERS_FAILURE';

export const GET_RESTAURANT_ORDERS_REQUEST = 'GET_RESTAURANT_ORDERS_REQUEST';
export const GET_RESTAURANT_ORDERS_SUCCESS = 'GET_RESTAURANT_ORDERS_SUCCESS';
export const GET_RESTAURANT_ORDERS_FAILURE = 'GET_RESTAURANT_ORDERS_FAILURE';
